config/routes.rb
Rails.application.routes.draw do
  resources :foodmenus
  resources :foods
  devise_for :users
  resources :restaurents
  resources :menus
  resources :menus
  resources :menus
  resources :menus
  resources :posts
  root 'static_pages#home'
  resources :todos
  resources :menus
  resources :restaurants

end

app/models/foodmenu.rb
class Foodmenu < ActiveRecord::Base
	belongs_to :restaurent
end

app/controllers/foodmenus_controller.rb
class FoodmenusController < ApplicationController
  before_action :set_foodmenu, only: [:show, :edit, :update, :destroy]

  # GET /foodmenus
  # GET /foodmenus.json
  def index
    @foodmenus = Foodmenu.all
  end

  # GET /foodmenus/1
  # GET /foodmenus/1.json
  def show
  end

  # GET /foodmenus/new
  def new
    @foodmenu = Foodmenu.new
  end

  # GET /foodmenus/1/edit
  def edit
  end

  # POST /foodmenus
  # POST /foodmenus.json
  def create
    @foodmenu = Foodmenu.new(foodmenu_params)

    respond_to do |format|
      if @foodmenu.save
        format.html { redirect_to @foodmenu, notice: 'Foodmenu was successfully created.' }
        format.json { render :show, status: :created, location: @foodmenu }
      else
        format.html { render :new }
        format.json { render json: @foodmenu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodmenus/1
  # PATCH/PUT /foodmenus/1.json
  def update
    respond_to do |format|
      if @foodmenu.update(foodmenu_params)
        format.html { redirect_to @foodmenu, notice: 'Foodmenu was successfully updated.' }
        format.json { render :show, status: :ok, location: @foodmenu }
      else
        format.html { render :edit }
        format.json { render json: @foodmenu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodmenus/1
  # DELETE /foodmenus/1.json
  def destroy
    @foodmenu.destroy
    respond_to do |format|
      format.html { redirect_to foodmenus_url, notice: 'Foodmenu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodmenu
      @foodmenu = Foodmenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foodmenu_params
      params.require(:foodmenu).permit(:name, :price, :restaurent_id)
    end
end

app/helpers/foodmenus_helper.rb
module FoodmenusHelper
end

app/views/foodmenus/_form.html.erb
<%= form_for(@foodmenu) do |f| %>
  <% if @foodmenu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foodmenu.errors.count, "error") %> prohibited this foodmenu from being saved:</h2>

      <ul>
      <% @foodmenu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <!-- Add this --> 
<%= f.text_field :restaurent_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foodmenus/edit.html.erb
<h1>Editing Foodmenu</h1>

<%= render 'form' %>

<%= link_to 'Show', @foodmenu %> |
<%= link_to 'Back', foodmenus_path %>

app/views/foodmenus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foodmenus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foodmenus.each do |foodmenu| %>
      <tr>
        <td><%= foodmenu.name %></td>
        <td><%= foodmenu.price %></td>
        <td><%= link_to 'Show', foodmenu %></td>
        <td><%= link_to 'Edit', edit_foodmenu_path(foodmenu) %></td>
        <td><%= link_to 'Destroy', foodmenu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foodmenu', new_foodmenu_path %>

app/views/foodmenus/new.html.erb
<h1>New Foodmenu</h1>

<%= render 'form' %>

<%= link_to 'Back', foodmenus_path %>

app/views/foodmenus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @foodmenu.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @foodmenu.price %>
</p>

<%= link_to 'Edit', edit_foodmenu_path(@foodmenu) %> |
<%= link_to 'Back', foodmenus_path %>