config/routes.rb
Rails.application.routes.draw do
  resources :foodmenus
  resources :foods
  devise_for :users
  resources :restaurents
  resources :menus
  resources :menus
  resources :menus
  resources :menus
  resources :posts
  root 'static_pages#home'
  resources :todos
  resources :menus
  resources :restaurants

end

app/models/restaurent.rb
class Restaurent < ActiveRecord::Base
	has_many :foodmenus
end

app/controllers/restaurents_controller.rb
class RestaurentsController < ApplicationController
  before_action :set_restaurent, only: [:show, :edit, :update, :destroy]

  # GET /restaurents
  # GET /restaurents.json
  def index
    @restaurents = Restaurent.all
  end

  # GET /restaurents/1
  # GET /restaurents/1.json
  def show
  @restaurent = Restaurent.find(params[:id])   # find post with id from params
  @foodmenus = @restaurent.foodmenus.all   # find all comments from current post
  @foodmenu = @restaurent.foodmenus.build  # Since we are now in post controller this line
                                   # is to pass comment model to comments/form

  end

  # GET /restaurents/new
  def new
    @restaurent = Restaurent.new
  end

  # GET /restaurents/1/edit
  def edit
  end

  # POST /restaurents
  # POST /restaurents.json
  def create
    @restaurent = Restaurent.new(restaurent_params)

    respond_to do |format|
      if @restaurent.save
        format.html { redirect_to @restaurent, notice: 'Restaurent was successfully created.' }
        format.json { render :show, status: :created, location: @restaurent }
      else
        format.html { render :new }
        format.json { render json: @restaurent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurents/1
  # PATCH/PUT /restaurents/1.json
  def update
    respond_to do |format|
      if @restaurent.update(restaurent_params)
        format.html { redirect_to @restaurent, notice: 'Restaurent was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurent }
      else
        format.html { render :edit }
        format.json { render json: @restaurent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurents/1
  # DELETE /restaurents/1.json
  def destroy
    @restaurent.destroy
    respond_to do |format|
      format.html { redirect_to restaurents_url, notice: 'Restaurent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurent
      @restaurent = Restaurent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurent_params
      params.require(:restaurent).permit(:name, :location)
    end
end

app/helpers/restaurents_helper.rb
module RestaurentsHelper
end

app/views/restaurents/_form.html.erb
<%= form_for(@restaurent) do |f| %>
  <% if @restaurent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurent.errors.count, "error") %> prohibited this restaurent from being saved:</h2>

      <ul>
      <% @restaurent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurents/edit.html.erb
<h1>Editing Restaurent</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurent %> |
<%= link_to 'Back', restaurents_path %>

app/views/restaurents/index.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1>Amazing Restaurents<small></small></h1>
</div>
<div class="table-responsive">
  <table class="table">
  <thead>
    <tr>

      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
            

    </tr>
  </thead>

  <tbody>
      <tr>
        <% @restaurents.each do |restaurent| %>
        <td><%= link_to restaurent.name, restaurent %></td>
        <td><%= restaurent.location %></td>
        <!-- <td><%= link_to 'Show', restaurent %></td> -->
        <td><%= link_to 'Edit', edit_restaurent_path(restaurent) if current_user.id == 1%></td>
      <!--<td><%= link_to 'Destroy', restaurent, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
  </table>
</div>
<%= link_to 'New Restaurent', new_restaurent_path %>
</div>

app/views/restaurents/new.html.erb
<h1>New Restaurent</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurents_path %>

app/views/restaurents/show.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">

<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><%= @restaurent.name %><small> - <%= @restaurent.location %></small></h1>
</div>

<hr/>
<h3>Comments</h3>
<% @foodmenus.each do |foodmenu| %> 
  <div>
    <strong>Name: </strong>
    <%= foodmenu.name %>
    <br />
    <strong>Comment: </strong>
  
    
  </div>
<% end %>
<%= render 'foodmenus/form' %>

<!-- <%= link_to 'Edit', edit_restaurent_path(@restaurent) %>  | -->
<%= link_to 'Back', restaurents_path %>
</div>